// <auto-generated />
namespace RoleLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewName));
        
        string IMigrationMetadata.Id
        {
            get { return "202002030045245_NewName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
